# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: in
    - name: Create local changes
      run: |
        cd in
        rm -rf .git
        rm -rf .github
        rm -rf .gitattributes
        cd ..
        cp -avr in out
        cd out
        ls -a
        
    - uses: actions/checkout@v2
      with:
        path: out2
        lfs: true
        repository: matrix3d/buildios
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - run: |
        cd out2
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config lfs.allowincompletepush true
        #git lfs track "*.a"
        #git add .
        #git commit -m "lfs"
        #git push
        echo jltttj >1.txt
        rm -rf v
        cd ..
        cp -avr in/. out2
        cd out2
        git add .
        git commit -m "push"
        git lfs push origin main
        git lfs push --all
        git push
        
