# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: in
    - name: Create local changes
      run: |
        cd in
        rm -rf .git
        rm -rf .github
        cd ..
        cp -avr in out
        cd out
        ls -a
        
    - uses: actions/checkout@v2
      with:
        path: out2
        repository: matrix3d/buildios
    - run: |
        cd out2
        echo jlj >1.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
        
