# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: in
    - name: Create local changes
      run: |
        cd in
        rm -rf .git
        rm -rf .github
        cd ..
        cp -avr in out
        cd out
        ls -a
        
    - uses: actions/checkout@v2
      with:
        path: out2
        lfs: true
        repository: matrix3d/buildios
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - run: |
        cp -avr in out2
        cd out2
        echo jltttj >1.txt
        rm -rf v
        git config lfs.allowincompletepush true
        git config user.name github-actions
        git config user.email github-actions@github.com
        git lfs track "*.a"
        git add .
        git commit -m "generated"
        git push
        
